### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by andreadelprete** [Gepetto/gepetto-viewer-corba#85] opened 2018-10-25 10:20 UTC
Hi everybody,

is there any plan to provide bindings for Python 3 in the near future? 
I've seen they are already available for Pinocchio, but not yet for gepetto-viewer.

**Comment by jcarpent** [comment] 2018-10-25 11:31
If I remember well, the issue is mostly coming from Corba. @jmirabel knows more the topic than me, it might be helpful to have his feedback on this point.

**Comment by andreadelprete** [comment] 2018-10-25 11:47
> We still have an issue with eigenpy which makes the python interpreter segfault on exiting in ubuntu < 18.04 / python3 < 3.6, so I am not even sure about the availability of Python3 in Pinocchio for now.

Actually this morning I've tested pinocchio on Ubuntu 14.04 with Python 3.4 and it seems to work

**Comment by jcarpent** [comment] 2018-10-25 11:53
@nim65s The segfault is certainly coming from Eigen allocator and destructor.
If you compile with C++11 one of the lib but not the other one, then the destructors won't be the same.

This issue has been referenced here stack-of-tasks/eigenpy#20

**Comment by jmirabel** [comment] 2018-10-25 11:58
The blocking point is omniORB. The support for Python 3 is from OmniORB 4.2.2. In 16.04, the version is 4.2.1. On 18.04, it is 4.2.2 but Ubuntu main repos do not provide python 3 support (See [this](https://bugs.launchpad.net/ubuntu/+source/python-omniorb/+bug/1781251)).

So to have it working you must:
- manually compile OmniORB 4.2.2 on Ubuntu 16.04 (which works fine I think),
- fix the CMake to install in the correct place (FINDPYTHON(3 REQUIRED) should work),
- fix silly conversion mistakes in Python scripts in this package.

For the first step, mind that you also need omniidl and omniidl-python...

**Comment by jmirabel** [comment] 2018-10-25 12:07
One remark: you do not have to compile gepetto-viewer-corba with omniORB 4.2.2. The only 2 things you need are:
- the files in `/usr/lib/python3/, similarly to the ones you have with `dpkg -L python-omniorb`
- the omniidl backend, similarly to the ones you have with `dpkg -L omniidl-python`

The second is needed at compile-time (when converting IDL file into python files). This would be easy to hack within this package.

**Comment by jmirabel** [comment] 2018-10-25 12:12
After digging up, it should be very easy to achieve !

- Download omniORBpy from the link above.
- in the `python3` folder inside the archive, there are two folders:
  - omniORB: which contains the files for the first point above
  - omniidl_be: which contains the file for the second point.

**Comment by andreadelprete** [comment] 2018-10-25 14:05
Thanks a lot for the detailed instructions @jmirabel ! One last thing: do you think that could work even on Ubuntu 14.04?

**Comment by jmirabel** [comment] 2018-10-25 14:13
I would way that omniORB has very few dependendies so it should work on Ubuntu 14.04. Anyway, it should be straightforward to verify (download and compile).

I may have been to optimistic when I said that there was nothing to compile. You still must compile omniORB 4.2.2.

**Comment by nim65s** [comment] 2018-10-25 14:23
if this is as easy as @jmirabel says, we can update omniorb's robotpkg version, and this will work on 14.04 for everyone

**Comment by jmirabel** [comment] 2018-10-25 14:28
Are you sure ? I though robotpkg was not meant to replace old packages already on ubuntu repos.

**Comment by jmirabel** [comment] 2018-10-25 14:28
Actually, you are right. If you provide only the python3 version of omniorb, then there are not conflicts !

**Comment by jmirabel** [comment] 2018-10-25 15:28
To compile the C++ code in gepetto-viewer-corba, either version of omniORB should work. It you compile it with omniORB 4.2.1 you will get the Python2 client generated and installed. The IDL files are also installed.

Then, in a post-processing step, generate Python3 client from installed IDL file with omniORBpy 4.2.2. You will have to copy the content of `src/gepetto` to `python3_path/gepetto` (may be with some changes to make it Python3 compatible).

**Comment by jmirabel** [comment] 2018-10-25 15:30
You need omniORBpy 4.2.2 to have a Python client. It manages the conversion between Python objects and omniORB objects send through network.

So to get omniORBpy, you need omniORB.

**Comment by andreadelprete** [comment] 2018-10-25 15:35
omniORB 4.2.2 has compiled just fine.
I'm not sure, but it seems to me that compiling directly gepetto-viewer-corba with omniORB4.2.2 might be simpler, because it doesn't require such a through understanding of the internal functioning of gepetto-viewer-corba. I' m gonna give it a try and keep you posted. Thanks!

**Comment by andreadelprete** [comment] 2018-10-25 16:02
Done, it seems to be working. In the end it was easier for me to recompile gepetto-viewer-corba with omniORB 4.2.2. These are the few things I had to fix in the python files:
 - in the `__init__.py` files, I had to specify full paths for the imports
 - in line 35 of `gepetto/corbaserver/client.py` I had to remove `, ex`

**Comment by jmirabel** [comment] 2018-10-25 16:33
Perfect ! Can you do a PR with the corrected Python files ?

**Comment by nim65s** [comment] 2018-10-25 16:59
@andreadelprete just to be sure… You get everything work with omniORB 4.2.2 *and* omniORBpy 4.2.2, right ?

**Comment by andreadelprete** [comment] 2018-10-25 19:41
> @andreadelprete just to be sure… You get everything work with omniORB 4.2.2 _and_ omniORBpy 4.2.2, right ?

yes, and python 3.4. tomorrow I'll do the PR.

**Comment by nim65s** [comment] 2018-10-26 13:53
fixed by #86

**Closed by nim65s** 2018-10-26 13:53 UTC
